// Package timeline provides ID-based recording and queries for operation timelines.
// Manager owns recording and persistence; callers own business results and exports.
package timeline

import (
	"github.com/compforge/go-stdx/timeline/manager"
	"github.com/compforge/go-stdx/timeline/model"
)

// Timeline is the optional object-style recording contract for one operation.
type Timeline = manager.Timeline

// StageHandle identifies a stage and supports ending it or updating its attributes.
type StageHandle = manager.StageHandle

// Attribute is recording input. Values must be JSON serializable and must not be
// mutated during the recording call.
type Attribute = manager.Attribute

// Actor optionally identifies the executor; ID and Name are independently optional.
type Actor = model.Actor

// StageID is an opaque identity generated by Begin or supplied for an external fact.
type StageID = model.StageID

// Status describes an observed stage or operation result.
type Status = model.Status

// Stage retains an interval, parentage, executor, attributes and business result.
type Stage = model.Stage

// Snapshot is a detached, JSON-serializable view with read-time collection status.
// Duration, RunningStages, LatestFailedStage and Summary query its recorded facts.
type Snapshot = model.Snapshot

// Collection reports local flush and store read success, not global completeness.
type Collection = model.Collection

var ErrInvalidStage = model.ErrInvalidStage
var ErrEmptyID = model.ErrEmptyID
var ErrInvalidAttribute = model.ErrInvalidAttribute
var ErrActiveStages = manager.ErrActiveStages
var ErrNotStarted = manager.ErrNotStarted

const (
	Unknown   = model.Unknown
	Running   = model.Running
	Succeeded = model.Succeeded
	Failed    = model.Failed
	Canceled  = model.Canceled
)
