// Package timeline defines a queryable timeline of an operation and its stages.
// Implementations own recording and snapshot synchronization; callers own the
// operation's business result and decide where snapshots are exported.
package timeline

import (
	"context"
	"errors"

	"github.com/compforge/go-stdx/timeline/model"
)

// Timeline is a recording handle for one business operation. Multiple handles
// may contribute through a shared store.Store. Methods and returned handles are safe
// for concurrent use. Business code owns completion and stage attribution.
type Timeline interface {
	// Record copies and buffers a completed stage. It performs no IO; Flush
	// confirms persistence. ID, name, actual start/end times and a terminal status
	// must be supplied. An omitted ParentID defaults to the root; a supplied parent
	// need not exist and is preserved for later association. Actor is preserved.
	// Repeated identical IDs are idempotent; conflicting persisted facts fail Flush.
	Record(Stage) error
	// Flush confirms this handle's preceding records reached its backend.
	// It does not wait for records buffered by other handles.
	Flush(context.Context) error
	// ID is the immutable, caller-supplied identity of this operation.
	// Its meaning and uniqueness scope belong to the caller.
	ID() string
	// SetAttributes records attributes on this handle's operation start.
	SetAttributes(attributes ...Attribute)
	// Begin starts a stage using the local clock unless source times are supplied.
	// Parentage is explicit; BeginWithContext is an optional context convenience.
	Begin(name string, opts ...StageOption) StageHandle
	// Snapshot flushes this handle and collects its backend's current facts.
	// Collection reports local flush and backend read success, never global
	// completeness. On error it returns best-effort data alongside the error.
	Snapshot(ctx context.Context) (Snapshot, error)
	// Finish records the operation result and returns a snapshot. Shared stores
	// accept late stage updates; a local backend may seal and return
	// ErrActiveStages until its stages end. The returned error is a collection
	// error, independent of operationErr. Finish never closes a shared store.Store.
	Finish(ctx context.Context, operationErr error) (Snapshot, error)
}

// StageHandle represents running work or a wait. A leaf stage is the basic
// recording unit of one component's execution flow: callers should begin and end
// it in the same goroutine. Parallel execution flows contribute separate stages.
// A parent stage may group parallel child stages across components; its own
// lifecycle remains owned by the coordinating component. A parent may end before
// its children.
type StageHandle interface {
	ID() StageID
	// SetAttributes merges attributes; the last value for a key wins.
	SetAttributes(attributes ...Attribute) error
	// End fixes the first valid result and submits it. A submission error may be
	// retried; after acceptance, later calls have no effect. A nil input error means
	// business success, while the returned error describes recording failure.
	End(err error, opts ...EndOption) error
}

var ErrInvalidStage = model.ErrInvalidStage

var ErrEmptyID = model.ErrEmptyID

var ErrInvalidAttribute = model.ErrInvalidAttribute

var ErrActiveStages = errors.New("timeline: operation still has active stages")

// Attribute is recording input. Values must be JSON serializable and must not be
// mutated during the recording call. Implementations encode them before returning.
type Attribute struct {
	Key   string `json:"key"`
	Value any    `json:"value"`
}

// Actor optionally identifies the executor; ID and Name are independently optional.
type Actor = model.Actor

// StageID is an opaque identity generated by Begin or supplied for an external fact.
type StageID = model.StageID

// Status describes an observed stage or operation result.
type Status = model.Status

// Stage retains an interval, parentage, executor, attributes and business result.
type Stage = model.Stage

// Snapshot is a detached, JSON-serializable view with read-time collection status.
// Duration, RunningStages, LatestFailedStage and Summary query its recorded facts.
type Snapshot = model.Snapshot

// Collection reports local flush and store read success, not global completeness.
type Collection = model.Collection

const (
	Unknown   = model.Unknown
	Running   = model.Running
	Succeeded = model.Succeeded
	Failed    = model.Failed
	Canceled  = model.Canceled
)

type contextKey struct{}

// NewContext optionally carries t without changing ctx's lifetime.
// Passing Timeline directly as a function argument needs no context binding.
func NewContext(ctx context.Context, t Timeline) context.Context {
	return context.WithValue(ctx, contextKey{}, t)
}

// FromContext retrieves a Timeline explicitly attached with NewContext.
// Constructors and Begin do not attach or replace this value.
func FromContext(ctx context.Context) (Timeline, bool) {
	if ctx == nil {
		return nil, false
	}
	t, ok := ctx.Value(contextKey{}).(Timeline)
	return t, ok && t != nil
}

// BeginWithContext is an optional adapter; Timeline itself does not require context
// binding. It preserves cancellation and only inherits a parent from this timeline.
func BeginWithContext(ctx context.Context, t Timeline, name string, opts ...StageOption) (context.Context, StageHandle) {
	if ref, ok := StageFromContext(ctx); ok && ref.TimelineID == t.ID() && ref.StageID != "" {
		opts = append([]StageOption{WithParent(ref.StageID)}, opts...)
	}
	stage := t.Begin(name, opts...)
	if stage.ID() == "" {
		return ctx, stage
	}
	return NewStageContext(ctx, StageRef{TimelineID: t.ID(), StageID: stage.ID()}), stage
}
