package manager

import (
	"context"
	"errors"

	"github.com/compforge/go-stdx/timeline/model"
)

// Timeline is a recording handle for one business operation. Multiple handles
// may contribute through a shared store.Store. Methods and returned handles are safe
// for concurrent use. Business code owns completion and stage attribution.
type Timeline interface {
	// Record copies and accepts a completed stage into the cache. Recording may
	// load Store on a miss; Flush confirms submission to the configured backend. ID, name, actual start/end times and a terminal status
	// must be supplied. An empty ParentID means no parent; a supplied parent
	// need not exist and is preserved for later association. Actor is preserved.
	// Repeated identical states are idempotent. The same ID with different actors
	// retains separate records; competing same-actor states use last accepted write.
	Record(Stage) error
	// Flush confirms preceding records reached the backend. A Manager-backed
	// handle checkpoints the shared local buffer for its operation ID.
	Flush(context.Context) error
	// ID is the immutable, caller-supplied identity of this operation.
	// Its meaning and uniqueness scope belong to the caller.
	ID() string
	// SetAttributes records attributes on this handle's operation start.
	SetAttributes(attributes ...Attribute)
	// Begin starts a stage using the local clock unless source times are supplied.
	// Parentage is explicit through WithParent; empty means no parent.
	Begin(name string, opts ...StageOption) StageHandle
	// Snapshot flushes this handle and collects its backend's current facts.
	// Collection reports local flush and backend read success, never global
	// completeness. On error it returns best-effort data alongside the error.
	Snapshot(ctx context.Context) (Snapshot, error)
	// Finish records the operation result and returns a snapshot. Shared stores
	// accept late stage updates; a local backend may seal and return
	// ErrActiveStages until its stages end. The returned error is a collection
	// error, independent of operationErr. Finish never closes a shared store.Store.
	Finish(ctx context.Context, operationErr error) (Snapshot, error)
}

// StageHandle captures a logical StageID and actor identity. Different actors
// may contribute to the same logical stage. Parent associations name logical
// stages and do not require any particular actor to finish first.
type StageHandle interface {
	ID() StageID
	// SetAttributes merges attributes; the last value for a key wins.
	SetAttributes(attributes ...Attribute) error
	// End fixes the first valid result and submits it. A submission error may be
	// retried; after acceptance, later calls have no effect. A nil input error means
	// business success, while the returned error describes recording failure.
	End(err error, opts ...EndOption) error
}

var ErrInvalidStage = model.ErrInvalidStage

var ErrEmptyID = model.ErrEmptyID

var ErrInvalidAttribute = model.ErrInvalidAttribute

var ErrActiveStages = errors.New("timeline: operation still has active stages")

// Attribute is recording input. Values must be JSON serializable and must not be
// mutated during the recording call. Implementations encode them before returning.
type Attribute struct {
	Key   string `json:"key"`
	Value any    `json:"value"`
}

// Actor identifies the executor; new records require ID or Name. ID takes precedence.
type Actor = model.Actor

// StageID is an opaque identity generated by Begin or supplied for an external fact.
type StageID = model.StageID

// Status describes an observed stage or operation result.
type Status = model.Status

// Stage retains an interval, parentage, executor, attributes and business result.
type Stage = model.Stage

// Snapshot is a detached, JSON-serializable view with read-time collection status.
// Duration, RunningStages, LatestFailedStage and Summary query its recorded facts.
type Snapshot = model.Snapshot

// Collection reports local flush and store read success, not global completeness.
type Collection = model.Collection

const (
	Unknown   = model.Unknown
	Running   = model.Running
	Succeeded = model.Succeeded
	Failed    = model.Failed
	Canceled  = model.Canceled
)

type contextKey struct{}

// NewContext optionally carries t without changing ctx's lifetime.
// Passing Timeline directly as a function argument needs no context binding.
func NewContext(ctx context.Context, t Timeline) context.Context {
	return context.WithValue(ctx, contextKey{}, t)
}

// FromContext retrieves a Timeline explicitly attached with NewContext.
// Constructors and Begin do not attach or replace this value.
func FromContext(ctx context.Context) (Timeline, bool) {
	if ctx == nil {
		return nil, false
	}
	t, ok := ctx.Value(contextKey{}).(Timeline)
	return t, ok && t != nil
}

// BeginWithContext is an optional adapter; Timeline itself does not require context
// binding. It preserves cancellation and binds the new stage identity. Parentage
// comes only from WithParent; the incoming context never supplies a parent.
func BeginWithContext(ctx context.Context, t Timeline, name string, opts ...StageOption) (context.Context, StageHandle) {
	stage := t.Begin(name, opts...)
	if stage.ID() == "" {
		return ctx, stage
	}
	return NewStageContext(ctx, StageRef{TimelineID: t.ID(), StageID: stage.ID()}), stage
}
